name: Deploy Nextcloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_FEDORABLE }}

    - name: Copy files to server
      run: |
        scp -r ./* user@192.168.1.100:/usr/share/nginx/html/nextcloud
        ssh user@192.168.1.100 'sudo chown -R nginx:nginx /usr/share/nginx/html/nextcloud'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
