name: Deploy Nextcloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.5.1' # Use the latest version of Node.js 20

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.6.0

      - name: Debug SSH Key
        run: echo "${{ secrets.SSH_PRIVATE_KEY_FEDORABLE }}" | head -n 1 | cut -c1-10

      - name: Add remote host to /etc/hosts
        run: echo "${{ secrets.FEDORABLE_IP }} Fedorable" | sudo tee -a /etc/hosts

      - name: Add remote host to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H Fedorable >> ~/.ssh/known_hosts

      - name: Ensure SSH connection is possible
        run: ssh -o StrictHostKeyChecking=no a
