name: Deploy Nextcloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Updated to the latest version

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4 # Updated to the latest version
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_FEDORABLE }}

    - name: Debug SSH Key
      run: echo "${{ secrets.SSH_PRIVATE_KEY_FEDORABLE }}" | head -n 1 | cut -c1-10

    - name: Ensure SSH connection is possible
      run: |
        ssh -o StrictHostKeyChecking=no abu-saif@Fedorable 'echo "SSH connection successful"'

    - name: Copy files to server
      run: |
        echo "Starting file copy..."
        scp -r ./* abu-saif@Fedorable:/usr/share/nginx/html/nextcloud
        echo "File copy completed."

    - name: Change ownership of files
      run: |
        echo "Changing file ownership..."
        ssh abu-saif@Fedorable 'sudo chown -R nginx:nginx /usr/share/nginx/html/nextcloud'
        echo "File ownership changed."
