name: Deploy Nextcloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_FEDORABLE }}

    - name: Debug SSH Key
      run: echo "${{ secrets.SSH_PRIVATE_KEY_FEDORABLE }}" | head -n 1 | cut -c1-10

    - name: Add remote host to /etc/hosts
      run: echo "${{ secrets.FEDORABLE_IP }} Fedorable" | sudo tee -a /etc/hosts

    - name: Add remote host to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H Fedorable >> ~/.ssh/known_hosts

    - name: Ensure SSH connection is possible
      run: ssh -o StrictHostKeyChecking=no abu-saif@Fedorable 'echo "SSH connection successful"'

    - name: Create nextcloud directory
      env:
        SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
      run: |
        ssh -o StrictHostKeyChecking=no abu-saif@Fedorable 'echo "${SUDO_PASSWORD}" | sudo -S mkdir -p /usr/share/nginx/html/nextcloud && sudo chown -R $USER:$USER /usr/share/nginx/html/nextcloud'

    - name: Copy files to server
      env:
        SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
      run: |
        echo "Starting file copy..."
        tar -czf - . | ssh -o StrictHostKeyChecking=no abu-saif@Fedorable 'echo "${SUDO_PASSWORD}" | sudo -S tar -xzf - -C /usr/share/nginx/html/nextcloud'

    - name: Change ownership of files
      env:
        SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
      run: |
        echo "Changing file ownership..."
        ssh -o StrictHostKeyChecking=no abu-saif@Fedorable 'echo "${SUDO_PASSWORD}" | sudo -S chown -R nginx:nginx /usr/share/nginx/html/nextcloud'
        echo "File ownership changed."
