name: Deploy Nextcloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_FEDORABLE }}

    - name: Debug SSH Key
      run: echo "${{ secrets.SSH_PRIVATE_KEY_FEDORABLE }}" | head -n 1 | cut -c1-10

    - name: Add remote host to /etc/hosts
      run: echo "${{ secrets.FEDORABLE_IP }} Fedorable" | sudo tee -a /etc/hosts

    - name: Add remote host to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H Fedorable >> ~/.ssh/known_hosts

    - name: Ensure SSH connection is possible
      run: ssh -o StrictHostKeyChecking=no abu-saif@Fedorable 'echo "SSH connection successful"'

    - name: Copy files to server
      run: |
        echo "Starting file copy..."
        scp -r ./* abu-saif@Fedorable:/usr/share/nginx/html/nextcloud
        echo "File copy completed."

    - name: Change ownership of files
      run: |
        echo "Changing file ownership..."
        ssh abu-saif@Fedorable 'sudo chown -R nginx:nginx /usr/share/nginx/html/nextcloud'
        echo "File ownership changed."
